#!/usr/bin/env bash

MIL_CONFIG=$1

ORIGINAL_CUDA_VISIBLE_DEVICES=$CUDA_VISIBLE_DEVICES
FIRST_DEVICE=$(echo $CUDA_VISIBLE_DEVICES | awk -F, '{print $1}')
MIL_CONFIG_FILENAME=$(basename $MIL_CONFIG)
MIL_CONFIG_FILENAME_WITHOUT_SUF="${MIL_CONFIG_FILENAME%.*}"
MIL_MODEL_PATH="mil_work_dirs/${MIL_CONFIG_FILENAME_WITHOUT_SUF}/latest.pth"
CUDA_VISIBLE_DEVICES=$FIRST_DEVICE python MIL/tools/test.py $MIL_CONFIG $MIL_MODEL_PATH --save_pred --metrics accuracy
CUDA_VISIBLE_DEVICES=$ORIGINAL_CUDA_VISIBLE_DEVICES