#!/usr/bin/env bash

MTL_CONFIG=$1

ORIGINAL_CUDA_VISIBLE_DEVICES=$CUDA_VISIBLE_DEVICES
FIRST_DEVICE=$(echo $CUDA_VISIBLE_DEVICES | awk -F, '{print $1}')
MTL_CONFIG_FILENAME=$(basename $MTL_CONFIG)
MTL_CONFIG_FILENAME_WITHOUT_SUF="${MTL_CONFIG_FILENAME%.*}"
MTL_MODEL_PATH="mtl_work_dirs/${MTL_CONFIG_FILENAME_WITHOUT_SUF}/latest.pth"
CUDA_VISIBLE_DEVICES=$FIRST_DEVICE python MTL/tools/test_with_visualization.py $MTL_CONFIG $MTL_MODEL_PATH --save_pt --inference
CUDA_VISIBLE_DEVICES=$ORIGINAL_CUDA_VISIBLE_DEVICES